### ISSUE TITLE
Hoobs support

### ISSUE THREAD

**Issue by matthewcouto** [donavanbecker/homebridge-honeywell-home-thermostat#35]
As you may know, Hoobs is running an older version of Homebridge so there's no way to use this plugin with Hoobs. They say it's the most recent stable version of Homebridge. Is there any way you can lower the version required to run this plugin? I've tested it with another system and it works great. Just what I need since native HomeKit support with the T5 is absolute garbage!

**Comment by donavanbecker** [comment]
@matthewcouto what are you running hoobs on?

**Comment by matthewcouto** [comment]
A RPi 4

**Comment by donavanbecker** [comment]
[Migrate From HOOBS To Homebridge](https://github.com/homebridge/homebridge-raspbian-image/wiki/How-To-Migrate-From-HOOBS-To-Homebridge), and you won't have these issues. 

I use to use HOOBs and always had these kinds of issues. HOOBs isn't using homebridge because if they would be then you wouldn't have this issue. since they take homebridge and change it how they want, they break this. If you use homebridge you will have the latest.

I develop this plugin for homebridge not HOOBs.

**Comment by donavanbecker** [comment]
@matthewcouto if you need help with moving over let me know!
